steps:
  # Default stack.yaml
  - command: "stack $ARGS build"
  - command: "stack $ARGS test"
  - command: "stack $ARGS haddock"

  # LTS 7
  - command: "stack $ARGS build"
    env:
      STACK_YAML: "stack-lts7.yaml"
  - command: "stack $ARGS test"
    env:
      STACK_YAML: "stack-lts7.yaml"

  # LTS 9
  - command: "stack $ARGS build"
    env:
      STACK_YAML: "stack-lts9.yaml"
  - command: "stack $ARGS test"
    env:
      STACK_YAML: "stack-lts9.yaml"


  # Latest LTS
  - command: "stack $ARGS build"
    env:
      ARGS: "--resolver lts"
  - command: "stack $ARGS test"
    env:
      ARGS: "--resolver lts"

  # Nightly build
  - command: "stack $ARGS build"
    env:
      ARGS: "--resolver nightly"
  - command: "stack $ARGS test"
    env:
      ARGS: "--resolver nightly"
